apiVersion: imp.dev/v1alpha1
kind: ImpVMClass
metadata:
  name: github-runner
spec:
  vcpu: 2
  memoryMiB: 2048
  diskGiB: 12
  arch: amd64
  tolerations:
    - key: imp.dev/runner
      operator: Equal
      value: "true"
      effect: NoSchedule
---
apiVersion: imp.dev/v1alpha1
kind: ImpNetwork
metadata:
  name: github-runner
  namespace: imp-system
spec:
  subnet: 192.168.230.0/24
  dns:
    - 169.254.169.254
    - 10.10.210.1
  nat:
    enabled: true
---
apiVersion: imp.dev/v1alpha1
kind: ImpVMTemplate
metadata:
  name: github-runner
  namespace: imp-system
spec:
  classRef:
    name: github-runner
  image: ghcr.io/syscode-labs/imp-runner-base@sha256:2eff35dfb047cdca1c396825a87cf5abbaa09a0115f539104fc256696c05fea8
  networkRef:
    name: github-runner
---
apiVersion: imp.dev/v1alpha1
kind: ImpVMRunnerPool
metadata:
  name: github-runner
  namespace: imp-system
spec:
  templateName: github-runner
  runnerLayer: ghcr.io/syscode-labs/imp-runner-layer@sha256:c8e0ffd4e719d0eb2c09d585801a46e300d773bc204deea0cdc2d568761b6e0a
  platform:
    type: github-actions
    tokenSource: github_app
    scope:
      org: syscode-labs
    runnerGroup: omni-runner
    credentialsSecret: github-imp-runners
  scaling:
    mode: polling
    minIdle: 1
    maxConcurrent: 1
    scaleUpStep: 1
    cooldownSeconds: 30
    polling:
      intervalSeconds: 30
