apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: "1.17.1"
      helm:
        valueFiles:
          - $values/infrastructure/cilium/values.yaml
    - repoURL: https://github.com/syscode-labs/syscode-homelab-gitops-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
