apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: oci-pivot-controller-config
  namespace: oci-pivot-system
spec:
  organizationId: "REPLACE_ME"
  projectId: "REPLACE_ME"
  secretName: oci-pivot-controller-config
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "REPLACE_ME"
      secretKeyName: OCI_COMPARTMENT_ID
