apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-pivot-controller-config
  namespace: oci-pivot-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-oci
    kind: ClusterSecretStore
  target:
    name: oci-pivot-controller-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: OCI_COMPARTMENT_ID
      remoteRef:
        key: "682a49f1-33b1-473b-96d9-b4b7009ebbfd" # gitleaks:allow -- Bitwarden secret UUID, not a credential
