apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/syscode-labs/imp.git
      targetRevision: f0c11704a101aaf97ed6ce61f0298942548674a5 # v0.6.1
      path: charts/imp
      helm:
        releaseName: imp
        valueFiles:
          - $values/values/clusters/unraid-lab/imp.yaml
    - repoURL: https://github.com/syscode-labs/syscode-homelab-gitops-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: imp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
