apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: argocd-pocketid-oidc
  namespace: argocd
spec:
  organizationId: "28d10c96-b6fb-4e33-b486-b1f700017837"
  projectId: "8e33ca9c-37d5-4437-a977-b4a101001e2f"
  secretName: argocd-pocketid-oidc
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "e8ae167f-f0c8-49c7-be92-0114a1ade320" # gitleaks:allow -- Bitwarden secret UUID, not a credential
      secretKeyName: clientSecret
