apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-object-storage
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-oci
    kind: ClusterSecretStore
  target:
    name: harbor-object-storage
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
      remoteRef:
        key: "8c171122-260d-4229-bdd0-b4b8016531ff" # gitleaks:allow -- Bitwarden secret UUID
    - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
      remoteRef:
        key: "d5a48f1c-a6da-49b6-9320-b4b80165323b" # gitleaks:allow -- Bitwarden secret UUID
