apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: unraid-lab-lan
  labels:
    advertise: unraid-lab-lan
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          syscode.dev/lan-vip: "true"
