apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: unraid-lab
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
    - name: unraid-lab-cilium
      localASN: 65001
      peers:
        - name: wrt-london
          peerASN: 65000
          peerAddress: 100.125.63.88
          peerConfigRef:
            name: wrt-london
