apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: wrt-london
spec:
  timers:
    connectRetryTimeSeconds: 30
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: unraid-lab-lan
