apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-oci
    kind: ClusterSecretStore
  target:
    name: grafana-cloud
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: metrics-username
      remoteRef:
        key: "586aca5a-53d4-486f-9215-b4a3012b4d6e" # gitleaks:allow
    - secretKey: metrics-password
      remoteRef:
        key: "0167adff-e881-4263-a8a6-b4a3012b4dac" # gitleaks:allow
    - secretKey: logs-username
      remoteRef:
        key: "1e7d563b-3318-4702-b5a3-b4a3012b4dea" # gitleaks:allow
    - secretKey: logs-password
      remoteRef:
        key: "a690572b-f1c1-4b3b-ae2e-b4a3012b4e2e" # gitleaks:allow
