apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-oci
    kind: ClusterSecretStore
  target:
    name: grafana-cloud
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: metrics-username
      remoteRef:
        key: "c2e46949-d7a7-47cd-9d27-b4b700eb8852" # gitleaks:allow
    - secretKey: metrics-password
      remoteRef:
        key: "5cf9423e-0767-4fb9-b3de-b4b700eb8981" # gitleaks:allow
    - secretKey: logs-username
      remoteRef:
        key: "eef52e57-b1a6-4efc-8fc1-b4b700eb8a45" # gitleaks:allow
    - secretKey: logs-password
      remoteRef:
        key: "5af64597-2c3d-4b13-aba1-b4b700eb8b11" # gitleaks:allow
