apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-oci
    kind: ClusterSecretStore
  target:
    name: grafana-cloud
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: metrics-username
      remoteRef:
        key: "d5957ce3-7d6d-416e-ab65-b4c3017929d3" # gitleaks:allow
    - secretKey: metrics-password
      remoteRef:
        key: "462e1be9-acb6-494d-9897-b4c3017791e2" # gitleaks:allow
    - secretKey: logs-username
      remoteRef:
        key: "eef52e57-b1a6-4efc-8fc1-b4b700eb8a45" # gitleaks:allow
    - secretKey: logs-password
      remoteRef:
        key: "5af64597-2c3d-4b13-aba1-b4b700eb8b11" # gitleaks:allow
