apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-lab-imp-namespace
  namespace: argocd
  labels:
    syscode.io/cluster: oci-lab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/syscode-labs/syscode-homelab-gitops-apps.git
    targetRevision: HEAD
    path: clusters/oci-lab/apps/imp-namespace/manifests
  destination:
    name: oci-lab
    namespace: imp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
