---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unraid-lab-cluster
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: unraid-lab-cluster
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      type: Opaque
      data:
        name: unraid-lab
        server: https://omni.wind-bearded.ts.net:8100
        config: |
          {"bearerToken": "{{ .token }}", "tlsClientConfig": {"insecure": false,
          "caData": "{{ .ca }}", "serverName": "omni.wind-bearded.ts.net"}}
  data:
    - secretKey: ca
      remoteRef:
        key: "000e2217-8d1b-415a-bdd5-b4b700f0392e" # gitleaks:allow
    - secretKey: token
      remoteRef:
        key: "973dd4ad-d5ca-4cf7-953b-b4b700f039b8" # gitleaks:allow
