apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-lab-argocd-rbac
  namespace: argocd
  labels:
    syscode.io/cluster: oci-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/syscode-labs/syscode-homelab-gitops-apps.git
    targetRevision: HEAD
    path: clusters/oci-lab/apps/argocd-rbac/manifests
  destination:
    name: oci-lab
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
